name: esp-lab
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bokeh
  - bottleneck
  - cartopy
  - climpred
  - cf-units
  - cftime
  - cmocean
  - dask
  - dask-jobqueue
  - distributed
  - dask-labextension
  - eofs
  - esmpy
  - holoviews
  - intake
  - intake-esm
  - ipykernel
  - ipywidgets
  - jupyter-server-proxy
  - jupyterlab
  - matplotlib
  - metpy
  - nc-time-axis
  - netcdf4
  - nodejs
  - notebook
  - numba
  - numpy
  - pandas
  - pint
  - pip
  - pcmdi_metrics
  - pop-tools
  - pre-commit
  - pytest
  - pytest-cov
  - python>=3.10
  - regionmask
  - scipy
  - seaborn
  - seawater
  - statsmodels
  - toolz
  - tqdm
  - watermark
  - xarray>=2023.1
  - xesmf # xarray interface to ESMF tools
  - xgcm # General Circulation Model Postprocessing with xarray
  - xhistogram # Fast, flexible, label-aware histograms for numpy and xarray
  - xrft # fourier transforms for xarray data
  - xskillscore>=0.0.24
  - zarr
  - ncar-jobqueue
