from esp_lab.diagnostics import (
    DEFAULT_CLIMATOLOGY_END_YEAR,
    DEFAULT_CLIMATOLOGY_START_YEAR,
    DEFAULT_CLIMATOLOGY_YEARS,
)


def test_default_climatology_is_1981_2010_thirty_year_normal():
    assert DEFAULT_CLIMATOLOGY_YEARS == (1981, 2010)
    assert DEFAULT_CLIMATOLOGY_START_YEAR == 1981
    assert DEFAULT_CLIMATOLOGY_END_YEAR == 2010
    assert DEFAULT_CLIMATOLOGY_END_YEAR - DEFAULT_CLIMATOLOGY_START_YEAR + 1 == 30
