#!/usr/bin/env python
"""Generate NMME regional SST-index time-series diagnostics.

This workflow reads the member-split NMME hindcast archive produced under
``data_hindcast_by_member/<model>/sst/M###/*.nc``, computes regional SST
indices using the same region set as the E3SM/CESM-SMYLE SST-index workflow,
and writes model-first time-series outputs. SST-index skill is computed by
``jupyter/4_refactor_sst_skill_ts.ipynb`` from these time series and the
HadISST2 indices generated by ``jupyter/0_run_sigmod_sst_index.ipynb``.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import warnings
from pathlib import Path
from uuid import uuid4

import cftime
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

from esp_lab import data_access_nmme as nmme_access
from esp_lab import stats
from esp_lab.diagnostics import (
    DEFAULT_CLIMATOLOGY_END_YEAR,
    DEFAULT_CLIMATOLOGY_START_YEAR,
)
from esp_lab.paths import NMME_DIAG_DIR, NMME_FIXED_DIR
from esp_lab.utils import calendar_utils as cal


DEFAULT_NMME_ROOT = Path("/global/cfs/cdirs/e3sm/S2S2D/NMME/data_hindcast_by_member")
DEFAULT_OUTDIR = NMME_DIAG_DIR
YEAGER_F03_MODELS = [
    "CMC1-CanCM3",
    "CMC2-CanCM4",
    "COLA-RSMAS-CCSM4",
    "GFDL-CM2p1-aer04",
    "GFDL-CM2p5-FLOR-A06",
    "GFDL-CM2p5-FLOR-B01",
    "NASA-GMAO-062012",
    "NCEP-CFSv2",
]
SPLIT_CLIMO_MODELS = {"COLA-RSMAS-CCSM4", "NCEP-CFSv2"}
INIT_MONTHS = [2, 5, 8, 11]
NINO34_LONLAT = [-170.0, -120.0, -5.0, 5.0]
VALID_REGIONS = [
    "IOD",
    "TNI",
    "ONI",
    "RONI",
    "Nino12",
    "Nino3",
    "Nino3.4",
    "Nino4",
    "TNA",
    "TSA",
    "PACWRAMPOOL",
    "AtlNino",
    "AtlMDR",
    "ELI",
]
REGIONS = {
    "Nino12": {"lonlat": [270.0, 280.0, -10.0, 0.0], "long_name": "Nino 1+2 regional mean SST"},
    "Nino3": {"lonlat": [210.0, 270.0, -5.0, 5.0], "long_name": "Nino 3 regional mean SST"},
    "Nino3.4": {"lonlat": [190.0, 240.0, -5.0, 5.0], "long_name": "Nino 3.4 regional mean SST"},
    "Nino4": {"lonlat": [160.0, 210.0, -5.0, 5.0], "long_name": "Nino 4 regional mean SST"},
    "TNA": {"lonlat": [305.0, 345.0, 5.0, 25.0], "long_name": "TNA regional mean SST"},
    "TSA": {"lonlat": [330.0, 10.0, -20.0, 0.0], "long_name": "TSA regional mean SST"},
    "PACWRAMPOOL": {"lonlat": [60.0, 170.0, -15.0, 15.0], "long_name": "PACWRAMPOOL regional mean SST"},
    "AtlNino": {"lonlat": [340.0, 360.0, -3.0, 3.0], "long_name": "Atlantic Nino regional mean SST"},
    "AtlMDR": {"lonlat": [280.0, 350.0, 10.0, 20.0], "long_name": "Atlantic MDR regional mean SST"},
    "IOD_West": {"lonlat": [50.0, 70.0, -10.0, 10.0], "long_name": "IOD West regional mean SST"},
    "IOD_East": {"lonlat": [90.0, 110.0, -10.0, 0.0], "long_name": "IOD East regional mean SST"},
    "TropicalMean": {"lonlat": [0.0, 360.0, -20.0, 20.0], "long_name": "Tropical Mean regional mean SST"},
}
SEASON_LABELS_BY_MONTH = {
    2: ["MAM", "JJA", "SON", "DJF", "MAM", "JJA", "SON"],
    5: ["JJA", "SON", "DJF", "MAM", "JJA", "SON", "DJF"],
    8: ["SON", "DJF", "MAM", "JJA", "SON", "DJF", "MAM"],
    11: ["DJF", "MAM", "JJA", "SON", "DJF", "MAM", "JJA"],
}
_S_CHUNK_RE = re.compile(r"_S(\d+)-(\d+)\.nc$")
ELI_ALGORITHM_VERSION = 2


def _date_slice_start(year: int) -> str:
    return f"{year:04d}-01-01"


def _date_slice_end(year: int) -> str:
    return f"{year:04d}-12-30"


def _period_tag(data_start: int, data_end: int) -> str:
    return f"{data_start:04d}_{data_end:04d}"


def _sst_index_dir(outdir: Path, category: str) -> Path:
    """Return a model-first NMME SST-index diagnostic directory."""
    return Path(outdir) / "sst_index" / category


def _region_token(region: str) -> str:
    return region.replace(".", "")


def _index_file_label(region: str) -> str:
    token = _region_token(region)
    return "ELI" if region == "ELI" else f"{token}SST"


def _region_dir(outdir: Path, region: str, category: str) -> Path:
    return _sst_index_dir(outdir, category)


def _required_base_regions(regions: list[str]) -> list[str]:
    required: set[str] = set()
    for region in regions:
        if region == "IOD":
            required.update(["IOD_West", "IOD_East"])
        elif region == "TNI":
            required.update(["Nino12", "Nino4"])
        elif region == "ONI":
            required.add("Nino3.4")
        elif region == "RONI":
            required.update(["Nino3.4", "TropicalMean"])
        elif region == "ELI":
            continue
        elif region in REGIONS:
            required.add(region)
    return sorted(required)


def _write_netcdf_replace(
    ds: xr.Dataset,
    path: Path,
    *,
    encoding: dict | None = None,
) -> None:
    """Write to a fresh temporary file, then replace the target path."""
    path = Path(path)
    tmp_path = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    try:
        ds.to_netcdf(tmp_path, encoding=encoding)
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def _decode_cf_time(ds: xr.Dataset, time_var: str = "S") -> xr.Dataset:
    ds = ds.copy()
    if ds[time_var].attrs.get("calendar") == "360":
        ds[time_var].attrs["calendar"] = "360_day"
    return xr.decode_cf(ds, decode_times=True)


def _member_number(member_dir: Path) -> int:
    return int(member_dir.name.removeprefix("M"))


def _sorted_member_dirs(model_dir: Path) -> list[Path]:
    dirs = [p for p in (model_dir / "sst").glob("M*") if p.is_dir()]
    return sorted(dirs, key=_member_number)


def discover_sst_models(root: Path) -> list[str]:
    """Discover downloaded NMME SST models in the member-split archive."""
    models = []
    for model_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        if model_dir.name == "logs":
            continue
        if _sorted_member_dirs(model_dir):
            models.append(model_dir.name)
    return models


def _chunk_range(path: Path) -> tuple[int, int] | None:
    match = _S_CHUNK_RE.search(path.name)
    if match is None:
        return None
    return int(match.group(1)), int(match.group(2))


def _decode_s_edge(path: Path, *, first: bool) -> object:
    with xr.open_dataset(path, decode_times=False) as ds:
        s_ds = ds[["S"]].copy()
    if s_ds["S"].attrs.get("calendar") == "360":
        s_ds["S"].attrs["calendar"] = "360_day"
    values = xr.decode_cf(s_ds, decode_times=True)["S"].values
    return values[0 if first else -1]


def model_s_range(root: Path, model: str) -> tuple[object, object]:
    """Return the decoded first and last initialization dates for one model."""
    files = []
    for path in (root / model / "sst").glob("M*/*.nc"):
        chunk_range = _chunk_range(path)
        if chunk_range is not None:
            files.append((*chunk_range, path))
    if not files:
        raise FileNotFoundError(f"No SST chunks found for {model} under {root / model / 'sst'}")

    first_file = min(files, key=lambda item: (item[0], item[1]))[2]
    last_file = max(files, key=lambda item: (item[1], item[0]))[2]
    return _decode_s_edge(first_file, first=True), _decode_s_edge(last_file, first=False)


def resolve_data_years(
    root: Path,
    models: list[str],
    data_start: str,
    data_end: str,
) -> tuple[int, int]:
    """Resolve explicit or auto data-window years for the selected models."""
    starts = []
    ends = []
    if data_start == "auto" or data_end == "auto":
        for model in models:
            start, end = model_s_range(root, model)
            starts.append(start.year)
            ends.append(end.year)

    resolved_start = min(starts) if data_start == "auto" else int(data_start)
    resolved_end = max(ends) if data_end == "auto" else int(data_end)
    if resolved_start > resolved_end:
        raise ValueError(f"data-start ({resolved_start}) must be <= data-end ({resolved_end})")
    return resolved_start, resolved_end


def _open_member_sst(
    member_dir: Path,
    model: str,
    data_start: int,
    data_end: int,
    *,
    apply_land_mask: bool,
    fixed_dir: Path,
) -> xr.Dataset:
    files = sorted(member_dir.glob(f"sst_{model}_{member_dir.name}_S*.nc"))
    if not files:
        raise FileNotFoundError(f"No SST chunks found under {member_dir}")
    ds = xr.open_mfdataset(
        files,
        combine="by_coords",
        decode_times=False,
        chunks={"S": 12, "L": -1, "Y": 181, "X": 360},
        parallel=False,
    )
    ds = _decode_cf_time(ds, "S")
    ds = ds.sel(S=slice(_date_slice_start(data_start), _date_slice_end(data_end)))
    ds["sst"] = nmme_access.mask_invalid_sst(
        ds["sst"],
        apply_land_mask=apply_land_mask,
        lon_name="X",
        lat_name="Y",
        model=model,
        fixed_dir=fixed_dir,
    )
    return ds


def _regional_mean(ds: xr.Dataset, lonlat: list[float]) -> xr.DataArray:
    lon_w, lon_e, lat_s, lat_n = lonlat
    lon1 = lon_w % 360.0
    lon2 = lon_e % 360.0
    lat_slice = slice(lat_s, lat_n)
    if (lon_e - lon_w) % 360 == 0:
        tmp = ds["sst"].sel(Y=lat_slice)
    elif lon1 <= lon2:
        tmp = ds["sst"].sel(Y=lat_slice, X=slice(lon1, lon2))
    else:
        tmp = xr.concat(
            [
                ds["sst"].sel(Y=lat_slice, X=slice(lon1, 360.0)),
                ds["sst"].sel(Y=lat_slice, X=slice(0.0, lon2)),
            ],
            dim="X",
        )
    weights = np.cos(np.deg2rad(tmp["Y"]))
    return tmp.weighted(weights).mean(("X", "Y"), skipna=True).rename("sst")


def _with_lon_0_360(da: xr.DataArray, lon_name: str) -> xr.DataArray:
    lon = (da[lon_name] % 360.0).astype(da[lon_name].dtype)
    return da.assign_coords({lon_name: lon}).sortby(lon_name)


def _eli_from_sst(sst: xr.DataArray, lon_name: str, lat_name: str) -> xr.DataArray:
    """Compute the equatorial longitude index from a regular SST grid."""
    sst = _with_lon_0_360(sst, lon_name)
    sst = sst.where(np.isfinite(sst))

    lat_slice = slice(-5.0, 5.0)
    tropical = sst.sel({lat_name: lat_slice})
    pacific = sst.sel({lat_name: lat_slice, lon_name: slice(120.0, 290.0)})
    tc = tropical.weighted(np.cos(np.deg2rad(tropical[lat_name]))).mean((lon_name, lat_name), skipna=True)

    lat_weights = xr.DataArray(
        np.cos(np.deg2rad(pacific[lat_name])),
        dims=(lat_name,),
        coords={lat_name: pacific[lat_name]},
    )
    cell_weights = xr.ones_like(pacific) * lat_weights
    warm_weights = cell_weights.where((pacific > tc) & pacific.notnull())
    weight_sum = warm_weights.sum((lon_name, lat_name), skipna=True)
    eli = (warm_weights * pacific[lon_name]).sum((lon_name, lat_name), skipna=True) / weight_sum
    return eli.where(weight_sum > 0).rename("sst").assign_attrs(
        long_name="Equatorial Longitude Index",
        region="ELI",
        units="degrees_east",
    )


def _model_eli(ds: xr.Dataset) -> xr.DataArray:
    return _eli_from_sst(ds["sst"], "X", "Y")


def _remove_init_month_climatology(
    regsst: xr.DataArray,
    model: str,
    clim_start: int,
    clim_end: int,
) -> xr.DataArray:
    def remove_period_climatology(part: xr.DataArray) -> xr.DataArray:
        in_climatology = (part["S"].dt.year >= clim_start) & (part["S"].dt.year <= clim_end)
        climatology = part.where(in_climatology, drop=True)
        if climatology.sizes.get("S", 0) == 0:
            raise ValueError(
                f"{model} has no initialization dates in the "
                f"{clim_start}-{clim_end} climatology window"
            )
        monthly_mean = climatology.groupby("S.month").mean(("S", "M"), skipna=True)
        return part.groupby("S.month") - monthly_mean

    if model in SPLIT_CLIMO_MODELS:
        parts = []
        for start, end in [(None, "1998-12-30"), ("1999-01-01", None)]:
            part = regsst.sel(S=slice(start, end))
            if part.sizes.get("S", 0) > 0:
                parts.append(remove_period_climatology(part))
        if parts:
            return xr.concat(parts, dim="S").sortby("S")
    return remove_period_climatology(regsst)


def _standardize_model_index(da: xr.DataArray, clim_start: int, clim_end: int) -> xr.DataArray:
    clim = da.where((da["S"].dt.year >= clim_start) & (da["S"].dt.year <= clim_end))
    dims = [dim for dim in ("S", "M") if dim in da.dims]
    sigma = clim.std(dim=dims, skipna=True)
    sigma = sigma.where(sigma > 0, 1.0)
    return da / sigma


def _derive_model_indices(
    base: dict[str, xr.DataArray],
    regions: list[str],
    clim_start: int,
    clim_end: int,
) -> dict[str, xr.DataArray]:
    derived: dict[str, xr.DataArray] = {}
    if "IOD" in regions and {"IOD_West", "IOD_East"}.issubset(base):
        derived["IOD"] = (base["IOD_West"] - base["IOD_East"]).assign_attrs(
            long_name="Dipole Mode Index (IOD West SST anomaly minus IOD East SST anomaly)",
            region="IOD",
            units="degC",
            index_name="DMI",
            definition="anomaly(IOD_West SST) - anomaly(IOD_East SST)",
            climatology_start_year=clim_start,
            climatology_end_year=clim_end,
        )
    if "ONI" in regions and "Nino3.4" in base:
        derived["ONI"] = base["Nino3.4"].rolling(L=3, center=True, min_periods=1).mean().assign_attrs(
            long_name="Oceanic Nino Index (3-month running mean of Nino3.4 anomalies)",
            region="Nino3.4",
            units="degC",
        )
    if "TNI" in regions and {"Nino12", "Nino4"}.issubset(base):
        diff = _standardize_model_index(base["Nino12"], clim_start, clim_end) - _standardize_model_index(
            base["Nino4"], clim_start, clim_end
        )
        derived["TNI"] = diff.rolling(L=5, center=True, min_periods=1).mean().assign_attrs(
            long_name="Trans-Nino Index (standardized Nino12 minus standardized Nino4 with 5-month running mean)",
            region="TNI",
            units="1",
        )
    if "RONI" in regions and {"Nino3.4", "TropicalMean"}.issubset(base):
        nino34_3m = base["Nino3.4"].rolling(L=3, center=True, min_periods=1).mean()
        diff_3m = (base["Nino3.4"] - base["TropicalMean"]).rolling(L=3, center=True, min_periods=1).mean()
        clim_mask = (base["Nino3.4"]["S"].dt.year >= clim_start) & (base["Nino3.4"]["S"].dt.year <= clim_end)
        dims = [dim for dim in ("S", "M") if dim in diff_3m.dims]
        std_nino = nino34_3m.where(clim_mask).std(dim=dims, skipna=True)
        std_diff = diff_3m.where(clim_mask).std(dim=dims, skipna=True)
        ratio = (std_nino / std_diff).fillna(1.0).where(std_diff > 0, 1.0)
        derived["RONI"] = (diff_3m * ratio).assign_attrs(
            long_name="Relative Oceanic Nino Index",
            region="RONI",
            units="degC",
        )
    return derived


def load_or_compute_model_regsst(
    root: Path,
    outdir: Path,
    model: str,
    region: str,
    data_start: int,
    data_end: int,
    clim_start: int,
    clim_end: int,
    *,
    force: bool = False,
    apply_land_mask: bool = True,
    fixed_dir: Path = NMME_FIXED_DIR,
) -> xr.DataArray:
    period = _period_tag(data_start, data_end)
    label = _index_file_label(region)
    cache_suffix = (
        f"{label}_mon_{period}.nc"
        if region == "ELI"
        else f"{label}_mon_anom_{period}_clim{clim_start}-{clim_end}.nc"
    )
    cache_file = _region_dir(outdir, region, "processed") / f"NMME_{model}_{cache_suffix}"
    if cache_file.exists() and not force:
        cached_dataset = xr.open_dataset(cache_file)
        cached = cached_dataset["sst"]
        cache_is_current = (
            cached.attrs.get("nmme_sst_mask_version")
            == nmme_access.NMME_SST_MASK_VERSION
            and cached.attrs.get("nmme_sst_land_mask")
            == str(bool(apply_land_mask))
        )
        if region == "ELI":
            cache_is_current = cache_is_current and (
                cached.attrs.get("eli_algorithm_version") == ELI_ALGORITHM_VERSION
            )
        if cache_is_current:
            return cached
        cached_dataset.close()

    model_dir = root / model
    if not model_dir.is_dir():
        raise FileNotFoundError(f"Model directory not found: {model_dir}")

    required_base = _required_base_regions([region])
    members_by_region = {base_region: [] for base_region in required_base}
    eli_members = []
    member_ids = []
    for member_dir in _sorted_member_dirs(model_dir):
        member_id = _member_number(member_dir)
        print(f"[NMME] {model} {member_dir.name}")
        with _open_member_sst(
            member_dir,
            model,
            data_start,
            data_end,
            apply_land_mask=apply_land_mask,
            fixed_dir=fixed_dir,
        ) as ds:
            if region == "ELI":
                eli_members.append(_model_eli(ds).load())
            else:
                for base_region in required_base:
                    members_by_region[base_region].append(_regional_mean(ds, REGIONS[base_region]["lonlat"]).load())
        member_ids.append(member_id)

    if not member_ids:
        raise ValueError(f"No members found for {model}")

    member_coord = xr.DataArray(member_ids, dims="M", name="M")
    if region == "ELI":
        regsst = xr.concat(eli_members, dim=member_coord)
        regsst = regsst.assign_coords(L=np.arange(regsst.sizes["L"]) + 1)
    else:
        base_anom = {}
        for base_region, members in members_by_region.items():
            regsst = xr.concat(members, dim=member_coord)
            regsst = regsst.assign_coords(L=np.arange(regsst.sizes["L"]) + 1)
            base_anom[base_region] = _remove_init_month_climatology(
                regsst,
                model,
                clim_start,
                clim_end,
            )
        all_indices = {**base_anom, **_derive_model_indices(base_anom, [region], clim_start, clim_end)}
        if region not in all_indices:
            raise ValueError(f"Could not compute requested NMME region {region!r}")
        regsst = all_indices[region]
    if region == "ELI":
        long_name = f"{model} NMME Equatorial Longitude Index"
    elif region == "IOD":
        long_name = f"{model} NMME Dipole Mode Index anomaly"
    else:
        long_name = f"{model} NMME {region} SST anomaly"
    regsst.attrs.update(
        {
            "long_name": long_name,
            "units": regsst.attrs.get("units", "degrees_east" if region == "ELI" else "degC"),
            "region": region,
            "source": str(model_dir),
            "data_start": data_start,
            "data_end": data_end,
            "climatology": (
                "raw longitude centroid; drift correction is applied downstream"
                if region == "ELI"
                else f"{clim_start}-{clim_end} init-month climatology removed before drift correction"
            ),
            **(
                {}
                if region == "ELI"
                else {
                    "climatology_start_year": clim_start,
                    "climatology_end_year": clim_end,
                }
            ),
            "nmme_sst_mask_version": nmme_access.NMME_SST_MASK_VERSION,
            "nmme_sst_land_mask": str(bool(apply_land_mask)),
            "valid_sst_mask": (
                "unit-aware physical SST bounds using archive scale_min when "
                "available"
            ),
        }
    )
    if region == "ELI":
        regsst.attrs.update(
            eli_algorithm_version=ELI_ALGORITHM_VERSION,
        )

    cache_file.parent.mkdir(parents=True, exist_ok=True)
    _write_netcdf_replace(
        regsst.to_dataset(name="sst"),
        cache_file,
        encoding={"S": {"units": "days since 1960-01-01", "calendar": "360_day"}},
    )
    print(f"[NMME] wrote {cache_file}")
    return regsst


def _add_months(year: int, month: int, offset: int) -> cftime.DatetimeNoLeap:
    month_index = month - 1 + offset
    return cftime.DatetimeNoLeap(year + month_index // 12, month_index % 12 + 1, 15)


def subset_init_month(da: xr.DataArray, init_month: int) -> tuple[xr.DataArray, xr.DataArray]:
    init_times = da["S"].where(da["S"].dt.month == init_month, drop=True)
    out = da.sel(S=init_times).rename({"S": "Y"}).assign_coords(Y=init_times.dt.year.data)
    out = out.assign_coords(L=np.arange(out.sizes["L"]) + 1)

    years = out["Y"].values.astype(int)
    leads = out["L"].values.astype(int)
    valid_time = xr.DataArray(
        np.array(
            [[_add_months(int(year), init_month, int(lead) - 1) for lead in leads] for year in years],
            dtype=object,
        ),
        dims=("Y", "L"),
        coords={"Y": years, "L": leads},
        name="time",
    )
    return out, valid_time


def _standardize_obs(ds: xr.Dataset, var: str) -> xr.DataArray:
    rename = {}
    if "latitude" in ds.coords:
        rename["latitude"] = "lat"
    if "longitude" in ds.coords:
        rename["longitude"] = "lon"
    ds = ds.rename(rename)
    if ds["lat"][0] > ds["lat"][-1]:
        ds = ds.reindex(lat=ds.lat[::-1])
    if ds["lon"].min() >= 0:
        lon = (((ds["lon"] + 180) % 360) - 180).astype(ds["lon"].dtype)
        ds = ds.assign_coords(lon=lon).sortby("lon")
    sst = ds[var]
    return xr.where(sst < -2.0, -1.8, sst)


def _obs_region_mean(sst: xr.DataArray, lonlat: list[float]) -> xr.DataArray:
    lon_w, lon_e, lat_s, lat_n = lonlat
    lon1 = ((lon_w + 180.0) % 360.0) - 180.0
    lon2 = ((lon_e + 180.0) % 360.0) - 180.0
    lat_slice = slice(lat_s, lat_n)
    if (lon_e - lon_w) % 360 == 0:
        tmp = sst.sel(lat=lat_slice)
    elif lon1 <= lon2:
        tmp = sst.sel(lat=lat_slice, lon=slice(lon1, lon2))
    else:
        tmp = xr.concat(
            [
                sst.sel(lat=lat_slice, lon=slice(lon1, 180.0)),
                sst.sel(lat=lat_slice, lon=slice(-180.0, lon2)),
            ],
            dim="lon",
        )
    weights = np.cos(np.deg2rad(tmp["lat"]))
    return tmp.weighted(weights).mean(("lon", "lat"), skipna=True).rename("sst")


def _obs_eli(sst: xr.DataArray) -> xr.DataArray:
    return _eli_from_sst(sst, "lon", "lat")


def _obs_anom(da: xr.DataArray, clim_start: int, clim_end: int) -> xr.DataArray:
    clim = da.sel(time=slice(f"{clim_start}-01-01", f"{clim_end}-12-31"))
    climo = clim.groupby("time.month").mean("time", skipna=True)
    return da.groupby("time.month") - climo


def _standardize_obs_index(da_anom: xr.DataArray, clim_start: int, clim_end: int) -> xr.DataArray:
    clim = da_anom.sel(time=slice(f"{clim_start}-01-01", f"{clim_end}-12-31"))
    sigma = clim.std("time", skipna=True)
    sigma = sigma.where(sigma > 0, 1.0)
    return da_anom / sigma


def _derive_obs_indices(
    base: dict[str, xr.DataArray],
    regions: list[str],
    clim_start: int,
    clim_end: int,
) -> dict[str, xr.DataArray]:
    derived: dict[str, xr.DataArray] = {}
    if "IOD" in regions and {"IOD_West", "IOD_East"}.issubset(base):
        west_anom = _obs_anom(base["IOD_West"], clim_start, clim_end)
        east_anom = _obs_anom(base["IOD_East"], clim_start, clim_end)
        derived["IOD"] = (west_anom - east_anom).assign_attrs(
            long_name="Dipole Mode Index (IOD West SST anomaly minus IOD East SST anomaly)",
            region="IOD",
            units="degC",
            index_name="DMI",
            definition="anomaly(IOD_West SST) - anomaly(IOD_East SST)",
            climatology_start_year=clim_start,
            climatology_end_year=clim_end,
        )
    if "ONI" in regions and "Nino3.4" in base:
        derived["ONI"] = _obs_anom(base["Nino3.4"], clim_start, clim_end).rolling(
            time=3, center=True, min_periods=1
        ).mean().assign_attrs(
            long_name="Oceanic Nino Index (3-month running mean of Nino3.4 anomalies)",
            region="Nino3.4",
            units="degC",
        )
    if "TNI" in regions and {"Nino12", "Nino4"}.issubset(base):
        nino12 = _standardize_obs_index(_obs_anom(base["Nino12"], clim_start, clim_end), clim_start, clim_end)
        nino4 = _standardize_obs_index(_obs_anom(base["Nino4"], clim_start, clim_end), clim_start, clim_end)
        derived["TNI"] = (nino12 - nino4).rolling(time=5, center=True, min_periods=1).mean().assign_attrs(
            long_name="Trans-Nino Index (standardized Nino12 minus standardized Nino4 with 5-month running mean)",
            region="TNI",
            units="1",
        )
    if "RONI" in regions and {"Nino3.4", "TropicalMean"}.issubset(base):
        nino34_anom = _obs_anom(base["Nino3.4"], clim_start, clim_end)
        trop_anom = _obs_anom(base["TropicalMean"], clim_start, clim_end)
        nino34_3m = nino34_anom.rolling(time=3, center=True, min_periods=1).mean()
        diff_3m = (nino34_anom - trop_anom).rolling(time=3, center=True, min_periods=1).mean()
        nino_clim = nino34_3m.sel(time=slice(f"{clim_start}-01-01", f"{clim_end}-12-31"))
        diff_clim = diff_3m.sel(time=slice(f"{clim_start}-01-01", f"{clim_end}-12-31"))
        std_nino = nino_clim.std("time", skipna=True)
        std_diff = diff_clim.std("time", skipna=True)
        ratio = (std_nino / std_diff).fillna(1.0).where(std_diff > 0, 1.0)
        derived["RONI"] = (diff_3m * ratio).assign_attrs(
            long_name="Relative Oceanic Nino Index",
            region="RONI",
            units="degC",
        )
    return derived


def load_obs_region(
    obs_file: Path,
    obs_var: str,
    region: str,
    clim_start: int,
    clim_end: int,
) -> tuple[xr.DataArray, xr.DataArray]:
    ds = xr.open_dataset(obs_file)
    sst = _standardize_obs(ds, obs_var).sel(time=slice("1960-01-01", "2022-12-31"))
    if region == "ELI":
        obs_mon = _obs_eli(sst).rename("sst")
    else:
        required_base = _required_base_regions([region])
        base = {base_region: _obs_region_mean(sst, REGIONS[base_region]["lonlat"]) for base_region in required_base}
        all_indices = {**base, **_derive_obs_indices(base, [region], clim_start, clim_end)}
        if region not in all_indices:
            raise ValueError(f"Could not compute observed region {region!r}")
        obs_mon = all_indices[region].rename("sst")
    obs_seas = obs_mon.rolling(time=3, min_periods=3, center=True).mean().dropna("time", how="all")
    return obs_mon.load(), obs_seas.load()


def process_nmme(
    root: Path,
    outdir: Path,
    models: list[str],
    region: str,
    data_start: int,
    data_end: int,
    clim_start: int,
    clim_end: int,
    *,
    force: bool = False,
    apply_land_mask: bool = True,
    fixed_dir: Path = NMME_FIXED_DIR,
) -> dict[str, dict[int, xr.DataArray] | xr.DataArray]:
    reg_models = []
    loaded_models = []
    for model in models:
        try:
            reg = load_or_compute_model_regsst(
                root,
                outdir,
                model,
                region,
                data_start,
                data_end,
                clim_start,
                clim_end,
                force=force,
                apply_land_mask=apply_land_mask,
                fixed_dir=fixed_dir,
            )
        except Exception as exc:
            warnings.warn(f"[NMME] skipping {model}: {exc}", stacklevel=2)
            continue
        reg_models.append(reg.expand_dims(model=[model]))
        loaded_models.append(model)

    if not reg_models:
        raise ValueError("No NMME models could be loaded")

    nmme_regsst = xr.concat(
        reg_models,
        dim="model",
        join="outer",
        coords="minimal",
        compat="override",
    )
    monthly = {}
    monthly_time = {}
    seasonal = {}
    seasonal_time = {}
    monthly_dd = {}
    seasonal_dd = {}
    monthly_drift = {}
    seasonal_drift = {}

    for init_month in INIT_MONTHS:
        da_mon, time_mon = subset_init_month(nmme_regsst, init_month)
        ds_mon = da_mon.to_dataset(name="sst")
        ds_mon["time"] = time_mon
        da_seas = cal.mon_to_seas_dask(ds_mon)["sst"]
        time_seas = ds_mon["time"].sel(L=da_seas["L"])

        dd_mon, drift_mon = stats.remove_drift(da_mon, time_mon, clim_start, clim_end)
        dd_seas, drift_seas = stats.remove_drift(da_seas, time_seas, clim_start, clim_end)

        monthly[init_month] = da_mon
        monthly_time[init_month] = time_mon
        seasonal[init_month] = da_seas
        seasonal_time[init_month] = time_seas
        monthly_dd[init_month] = dd_mon
        seasonal_dd[init_month] = dd_seas
        monthly_drift[init_month] = drift_mon
        seasonal_drift[init_month] = drift_seas

    return {
        "models": xr.DataArray(loaded_models, dims="model", name="model"),
        "monthly": monthly,
        "monthly_time": monthly_time,
        "seasonal": seasonal,
        "seasonal_time": seasonal_time,
        "monthly_dd": monthly_dd,
        "seasonal_dd": seasonal_dd,
        "monthly_drift": monthly_drift,
        "seasonal_drift": seasonal_drift,
        "data_start": data_start,
        "data_end": data_end,
        "climatology_start": clim_start,
        "climatology_end": clim_end,
        "region": region,
    }


def compute_nmme_skill(
    processed: dict[str, dict[int, xr.DataArray] | xr.DataArray],
    obs_mon: xr.DataArray,
    obs_seas: xr.DataArray,
    clim_start: int,
    clim_end: int,
) -> dict[str, xr.Dataset]:
    seas = {}
    seas_mmm = {}
    mon = {}
    mon_mmm = {}
    for init_month in INIT_MONTHS:
        seas[init_month] = stats.compute_skill_seasonal(
            processed["seasonal_dd"][init_month],
            processed["seasonal_time"][init_month],
            obs_seas,
            str(clim_start),
            str(clim_end),
            1,
            4,
            resamp=0,
            detrend=True,
        )
        seas_mmm[init_month] = stats.compute_skill_seasonal(
            processed["seasonal_dd"][init_month].mean("M").rename({"model": "M"}),
            processed["seasonal_time"][init_month],
            obs_seas,
            str(clim_start),
            str(clim_end),
            1,
            4,
            resamp=0,
            detrend=True,
        )
        mon[init_month] = stats.compute_skill_seasonal(
            processed["monthly_dd"][init_month],
            processed["monthly_time"][init_month],
            obs_mon,
            str(clim_start),
            str(clim_end),
            1,
            12,
            resamp=0,
            detrend=True,
            monthly=True,
        )
        mon_mmm[init_month] = stats.compute_skill_seasonal(
            processed["monthly_dd"][init_month].mean("M").rename({"model": "M"}),
            processed["monthly_time"][init_month],
            obs_mon,
            str(clim_start),
            str(clim_end),
            1,
            12,
            resamp=0,
            detrend=True,
            monthly=True,
        )

    startmonth = xr.DataArray(INIT_MONTHS, name="startmonth", dims="startmonth")
    return {
        "nmme_seas_skill": xr.concat([seas[m] for m in INIT_MONTHS], dim=startmonth),
        "nmme_seas_skill_mmm": xr.concat([seas_mmm[m] for m in INIT_MONTHS], dim=startmonth),
        "nmme_skill": xr.concat([mon[m] for m in INIT_MONTHS], dim=startmonth),
        "nmme_skill_mmm": xr.concat([mon_mmm[m] for m in INIT_MONTHS], dim=startmonth),
    }


def save_timeseries_outputs(
    outdir: Path,
    processed: dict[str, dict[int, xr.DataArray] | xr.DataArray],
) -> Path:
    period = _period_tag(processed["data_start"], processed["data_end"])
    region = str(processed["region"])
    label = _index_file_label(region)
    clim_start = int(processed["climatology_start"])
    clim_end = int(processed["climatology_end"])
    timeseries_dir = _region_dir(outdir, region, "timeseries")
    timeseries_dir.mkdir(parents=True, exist_ok=True)

    output_attrs = {
        "region": region,
        "climatology_start_year": clim_start,
        "climatology_end_year": clim_end,
    }
    if region == "IOD":
        output_attrs.update(
            {
                "index_name": "DMI",
                "definition": "anomaly(IOD_West SST) - anomaly(IOD_East SST)",
            }
        )

    for init_month in INIT_MONTHS:
        ds_mon = xr.Dataset(
            {
                "sst": processed["monthly_dd"][init_month],
                "time": processed["monthly_time"][init_month],
            }
        )
        ds_mon.attrs.update(output_attrs)
        ds_mon["sst"].attrs.update(output_attrs)
        _write_netcdf_replace(ds_mon, timeseries_dir / f"NMME{init_month:02d}_{label}_mon_dd_{period}.nc")

        ds_seas = xr.Dataset(
            {
                "sst": processed["seasonal_dd"][init_month],
                "time": processed["seasonal_time"][init_month],
            }
        )
        ds_seas.attrs.update(output_attrs)
        ds_seas["sst"].attrs.update(output_attrs)
        _write_netcdf_replace(ds_seas, timeseries_dir / f"NMME{init_month:02d}_{label}_seas_dd_{period}.nc")
    return timeseries_dir


def plot_f03_like(skill: dict[str, xr.Dataset], figdir: Path, data_start: int, data_end: int) -> Path:
    nmme_seas_skill = skill["nmme_seas_skill"]
    nmme_seas_skill_mmm = skill["nmme_seas_skill_mmm"]
    nmme_skill = skill["nmme_skill"]
    nmme_skill_mmm = skill["nmme_skill_mmm"]
    period_label = f"NMME ({data_start}-{data_end})"

    fig = plt.figure(figsize=(18, 20))
    plt.rcParams.update({"font.size": 14})
    leadsea = nmme_seas_skill.L - 2
    hindcasts = ["FEB init", "MAY init", "AUG init", "NOV init", "ALL init average"]
    figlabs = [["a.", "c.", "e.", "g.", "i."], ["b.", "d.", "f.", "h.", "j."]]
    nrow = 5
    ncol = 2

    for j, init_month in enumerate(INIT_MONTHS):
        ax = fig.add_subplot(nrow, ncol, j * 2 + 1)
        ax2 = fig.add_subplot(nrow, ncol, j * 2 + 2)
        ax.set_title(figlabs[0][j] + " " + hindcasts[j], loc="left")
        ax2.set_title(figlabs[1][j] + " " + hindcasts[j], loc="left")
        if j == 0:
            ax.set_title("ACC", loc="center")
            ax2.set_title("nRMSE", loc="center")

        tmp = nmme_seas_skill_mmm.sel(startmonth=init_month)
        ax.plot(tmp.L - 2, tmp.corr, color="r", linewidth=2, linestyle="--", label=period_label)
        ax.plot(tmp.L - 2, tmp.corr, color="r", marker="o", markersize=8, fillstyle="none", linestyle="none")
        ax.plot(tmp.L - 2, tmp.corr.where(tmp.pval < 0.1), color="r", marker="o", markersize=8, linestyle="none")
        ax2.plot(tmp.L - 2, tmp.rmse, color="r", linewidth=2, marker="o", markersize=8, linestyle="--")

        tmp = nmme_seas_skill.sel(startmonth=init_month)
        ax.fill_between(tmp.L.data - 2, tmp.corr.min("model"), tmp.corr.max("model"), fc="r", alpha=0.2)
        ax2.fill_between(tmp.L.data - 2, tmp.rmse.min("model"), tmp.rmse.max("model"), fc="r", alpha=0.2)

        xticklabs = [f"{int(leadsea[i].data)}:{SEASON_LABELS_BY_MONTH[init_month][i]}" for i in range(leadsea.sizes["L"])]
        for a, ylim, hline in [(ax, [0.1, 1.0], 0.5), (ax2, [0.2, 1.3], 1.0)]:
            a.set_xticks(leadsea)
            a.set_xticklabels(xticklabs)
            a.set_xlim([-0.5, 20])
            a.set_ylim(ylim)
            a.grid(True)
            a.axhline(y=hline, color="black")
        if j == 0:
            ax.legend(loc="lower left")

    ax = fig.add_subplot(nrow, ncol, 4 * 2 + 1)
    ax2 = fig.add_subplot(nrow, ncol, 4 * 2 + 2)
    ax.set_title(figlabs[0][4] + " " + hindcasts[4], loc="left")
    ax2.set_title(figlabs[1][4] + " " + hindcasts[4], loc="left")

    tmp = nmme_skill_mmm.mean("startmonth")
    ax.plot(tmp.L - 1, tmp.corr, color="r", linewidth=2, linestyle="--", label=period_label)
    ax.plot(tmp.L - 1, tmp.corr, color="r", marker="o", markersize=8, fillstyle="none", linestyle="none")
    ax.plot(tmp.L - 1, tmp.corr.where(tmp.pval < 0.1), color="r", marker="o", markersize=8, linestyle="none")
    ax2.plot(tmp.L - 1, tmp.rmse, color="r", linewidth=2, marker="o", markersize=8, linestyle="--")

    tmp = nmme_skill.mean("startmonth")
    ax.fill_between(tmp.L.data - 1, tmp.corr.min("model", skipna=True), tmp.corr.max("model", skipna=True), fc="r", alpha=0.2)
    ax2.fill_between(tmp.L.data - 1, tmp.rmse.min("model", skipna=True), tmp.rmse.max("model", skipna=True), fc="r", alpha=0.2)

    for a, ylim, hline in [(ax, [0.1, 1.0], 0.5), (ax2, [0.2, 1.3], 1.0)]:
        a.set_xticks(np.arange(12) * 2 + 1)
        a.set_xticks(np.arange(12) * 2, minor=True)
        a.set_xlim([-0.5, 24])
        a.set_ylim(ylim)
        a.grid(True)
        a.axhline(y=hline, color="black")

    fig.tight_layout()
    figdir.mkdir(parents=True, exist_ok=True)
    figpath = figdir / "fig_nmme_nino34_f03_skill.png"
    fig.savefig(figpath, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return figpath


def plot_f04_like(
    processed: dict[str, dict[int, xr.DataArray] | xr.DataArray],
    skill: dict[str, xr.Dataset],
    obs_seas: xr.DataArray,
    clim_start: int,
    clim_end: int,
    data_start: int,
    data_end: int,
    figdir: Path,
) -> Path:
    obs_djf = obs_seas.where(obs_seas.time.dt.month == 1, drop=True)
    obs_djf = obs_djf - obs_djf.sel(time=slice(str(clim_start), str(clim_end))).mean("time")

    sm_order = [11, 8, 5, 2]
    hindcasts = {11: "NOV", 8: "AUG", 5: "MAY", 2: "FEB"}
    lead_index = {11: 0, 8: 1, 5: 2, 2: 3}
    colors = {11: "g", 8: "orange", 5: "b", 2: "r"}
    figlabs = [["a.", "c.", "e.", "g."], ["b.", "d.", "f."]]

    fig = plt.figure(figsize=(11, 10))
    plt.rcParams.update({"font.size": 10})
    for i, init_month in enumerate(sm_order):
        panels = [(0, lead_index[init_month])]
        if i < 3:
            panels.append((1, lead_index[init_month] + 4))

        for col, lindex in panels:
            ax = fig.add_subplot(4, 2, i * 2 + col + 1)
            ax.set_ylim([-3.5, 3.5])
            ax.set_yticks([-2, 0, 2])
            ax.set_yticks(np.arange(-3.5, 4, 0.5), minor=True)
            xmin = min(1980, data_start)
            xmax = max(2022, data_end)
            ax.set_xlim([xmin, xmax])
            ax.set_xticks(np.arange(xmin, xmax + 2, 2), minor=True)
            ax.plot(obs_djf.time.dt.year, obs_djf, color="k", marker=".", markersize=6, label="HadISST2")

            if lindex >= processed["seasonal_dd"][init_month].sizes["L"]:
                ax.set_title(
                    f"{figlabs[col][i]} {hindcasts[init_month]} init: lead unavailable in 12-month NMME",
                    loc="left",
                )
                ax.grid(True)
                continue

            data = processed["seasonal_dd"][init_month].isel(L=lindex).mean("model")
            time = processed["seasonal_time"][init_month].isel(L=lindex)
            data_year = time.dt.year
            skill_row = skill["nmme_seas_skill_mmm"].sel(startmonth=init_month).isel(L=lindex)
            lead = int(data.L.values) - 2
            acc = float(skill_row.corr.values)
            nrmse = float(skill_row.rmse.values)
            figlabel = figlabs[col][i] if col == 0 else figlabs[col][i]
            title = f"{hindcasts[init_month]} init ({lead:d}-mon lead), ACC={acc:3.2f}, nRMSE={nrmse:3.2f}"
            ax.set_title(figlabel + " " + title, loc="left")

            mean = data.mean("M")
            spread = data.std("M")
            ax.plot(data_year, mean, color=colors[init_month], linewidth=2, label="NMME MMM")
            ax.fill_between(data_year, mean - spread, mean + spread, fc=colors[init_month], alpha=0.2)
            ax.grid(True)

    fig.suptitle(r"$DJF\;Ni\tilde{n}o-3.4\;Index$", fontsize=18)
    fig.tight_layout()
    figdir.mkdir(parents=True, exist_ok=True)
    figpath = figdir / "fig_nmme_nino34_f04_djf_timeseries.png"
    fig.savefig(figpath, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return figpath


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nmme-root", type=Path, default=DEFAULT_NMME_ROOT)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument(
        "--nmme-fixed-dir",
        type=Path,
        default=NMME_FIXED_DIR,
        help="Directory for reusable per-model NMME fixed fields.",
    )
    parser.add_argument(
        "--regions",
        nargs="+",
        default=VALID_REGIONS,
        help=f"SST indices/regions to compute. Default: {VALID_REGIONS}",
    )
    parser.add_argument(
        "--custom-regions",
        default=None,
        help="JSON string defining additional or overriding region lonlat boxes.",
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=None,
        help=(
            "Models to process. Defaults to every downloaded SST model under "
            "--nmme-root. Use --model-set yeager-f03 for the eight-model subset "
            "from Yeager f03_f04.ipynb."
        ),
    )
    parser.add_argument(
        "--model-set",
        choices=["all", "yeager-f03"],
        default="all",
        help="Named model set to use when --models is omitted.",
    )
    parser.add_argument(
        "--clim-start", type=int, default=DEFAULT_CLIMATOLOGY_START_YEAR
    )
    parser.add_argument("--clim-end", type=int, default=DEFAULT_CLIMATOLOGY_END_YEAR)
    parser.add_argument(
        "--data-start",
        default="1982",
        help="First initialization year to process, or 'auto' for the earliest selected-model data year.",
    )
    parser.add_argument(
        "--data-end",
        default="2016",
        help="Last initialization year to process, or 'auto' for the latest selected-model data year.",
    )
    parser.add_argument("--force", action="store_true")
    parser.add_argument(
        "--nmme-sst-land-mask",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Apply the Natural Earth land mask to NMME SST immediately after "
            "reading (default: enabled)."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    if args.custom_regions:
        REGIONS.update(json.loads(args.custom_regions))
    unknown_regions = sorted(set(args.regions) - set(VALID_REGIONS) - set(REGIONS))
    if unknown_regions:
        raise ValueError(f"Unknown --regions entries: {unknown_regions}")
    if args.models is None:
        if args.model_set == "yeager-f03":
            args.models = YEAGER_F03_MODELS
        else:
            args.models = discover_sst_models(args.nmme_root)

    data_start, data_end = resolve_data_years(
        args.nmme_root,
        args.models,
        args.data_start,
        args.data_end,
    )
    print(f"[NMME] data window: {data_start}-{data_end}")
    print(f"[NMME] skill climatology window: {args.clim_start}-{args.clim_end}")
    print(f"[NMME] processing {len(args.models)} model(s) from member-split archive")
    for region in args.regions:
        print(f"[NMME] processing region: {region}")
        processed = process_nmme(
            args.nmme_root,
            args.outdir,
            args.models,
            region,
            data_start,
            data_end,
            args.clim_start,
            args.clim_end,
            force=args.force,
            apply_land_mask=args.nmme_sst_land_mask,
            fixed_dir=args.nmme_fixed_dir,
        )
        timeseries_dir = save_timeseries_outputs(args.outdir, processed)
        print(f"Saved NMME SST-index time series under: {timeseries_dir}")


if __name__ == "__main__":
    main()
